# Generated by Django 6.1 on 2026-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produit_prix_alter_produit_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payee'), ('en_attente', 'En attente'), ('impayee', 'Impayee'), ('annulee', 'Annulee')], default='impayee', max_length=20),
        ),
    ]
