# Generated by Django 6.0.7 on 2026-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
    ]
