# Generated by Django 6.0.7 on 2026-08-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_is_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='is_actif',
        ),
    ]
