# Generated by Django 6.0.7 on 2026-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_produit_is_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_actif',
            field=models.BooleanField(default=False),
        ),
    ]
