# Generated by Django 6.0.7 on 2026-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_produit_is_actif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
