"""
Django settings for GestionPharmacie project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-awo^odn*$(7s@@l$3&7+0fj5$kcyygwdk_88(3s)$*bzv8ub!='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Chaque application activee dans le projet doit figurer ici :
# Django n'utilise que les apps listees (modeles, templates, fichiers
# statiques...). Les six premieres lignes sont des applications
# fournies par Django lui-meme (admin, authentification, sessions,
# messages flash, fichiers statiques...) ; 'products' est notre
# propre application, creee avec `python manage.py startapp products`.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',

]

# Une requete traverse cette liste de haut en bas avant d'atteindre la
# vue, puis a nouveau de bas en haut pour la reponse. Par exemple
# AuthenticationMiddleware est ce qui rend request.user disponible
# partout, et MessageMiddleware ce qui alimente la variable `messages`
# utilisee dans products/templates/partials/messages.html.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Indique a Django ou se trouve le fichier d'URLs racine du projet
# (voir GestionPharmacie/urls.py).
ROOT_URLCONF = 'GestionPharmacie.urls'

# Configuration du moteur de templates.
# - APP_DIRS: True -> Django cherche automatiquement un dossier
#   templates/ dans chaque application installee (ici
#   products/templates/), sans avoir besoin de le declarer dans DIRS.
# - context_processors -> variables injectees automatiquement dans le
#   contexte de CHAQUE template, sans que la vue ait besoin de les
#   passer explicitement : "request" (utilisee par ex. dans
#   partials/sidebar.html pour surligner le lien actif), "auth"
#   (rend `user` disponible) et "messages" (rend `messages`
#   disponible, voir partials/messages.html).
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestionPharmacie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite est utilise ici : une base de donnees legere stockee dans un
# seul fichier (db.sqlite3, a la racine du projet), ideale pour
# apprendre et developper en local sans installer de serveur de base
# de donnees a part. C'est cette configuration que l'ORM Django (les
# futurs modeles de products/models.py) utilisera pour lire/ecrire des
# donnees, via les commandes `makemigrations` puis `migrate`.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Prefixe d'URL sous lequel les fichiers statiques sont servis, ex.
# products/static/css/style.css devient /static/css/style.css. Dans
# les templates, on ne l'ecrit jamais en dur : {% load static %} puis
# {% static 'css/style.css' %} (voir base.html) generent l'URL a
# partir de ce reglage.
STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
